server:
  port: ${APP_PORT:8000}
  servlet:
    session:
      cookie:
        http-only: true
    context-path: /
    application-display-name: microservice
  tomcat:
    max-connections: 1000
    accept-count: 100
    connection-timeout: 30000

spring:
  application:
    name: microservice


scheduling:
  timeout:
    enabled: true
    interval: 5000


logging:
  level:
    ROOT: INFO
    com.arcmicroservices: DEBUG
    org.springframework: INFO

management:
  endpoints:
    web:
      exposure:
        include: info, health, metrics
  metrics:
    export:
      atlas:
        enabled: true

organization:
  maxUser: 10
