server:
  port: ${APP_PORT:8000}
  servlet:
    session:
      cookie:
        http-only: true
    context-path: /microservice
    application-display-name: microservice
  tomcat:
    max-connections: 1000
    accept-count: 100
    connection-timeout: 30000

spring:
  application:
    name: microservice
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: arcmicroservices
    password: arcmicroservices
    driverClassName: org.postgresql.Driver
    hikari:
      connection-timeout: 30000
      maximum-pool-size: 10
  liquibase:
    enabled: true
    change-log: classpath:/changelog/changelog-master.xml


logging:
  level:
    ROOT: INFO
    com.arcmicroservices: DEBUG
    org.springframework: INFO

management:
  endpoints:
    web:
      exposure:
        include: info, health, metrics
  atlas:
    metrics:
      export:
        enabled: true

organization:
  maxUser: 10
